//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq)] # [sea_orm (table_name = "audit_log")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , # [sea_orm (column_type = "Text")] pub table_name : String , # [sea_orm (column_type = "Text")] pub record_id : String , # [sea_orm (column_type = "Text")] pub operation : String , # [sea_orm (column_type = "JsonBinary" , nullable)] pub old_values : Option < Json > , # [sea_orm (column_type = "JsonBinary" , nullable)] pub new_values : Option < Json > , pub changed_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { }

impl ActiveModelBehavior for ActiveModel { }