//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel)] # [sea_orm (table_name = "measurement")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub time : DateTimeWithTimeZone , # [sea_orm (primary_key , auto_increment = false)] pub device_id : i32 , # [sea_orm (column_type = "Double")] pub value : f64 , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::device::Entity" , from = "Column::DeviceId" , to = "super::device::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Device , }

impl Related < super :: device :: Entity > for Entity { fn to () -> RelationDef { Relation :: Device . def () } }

impl ActiveModelBehavior for ActiveModel { }