//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq)] # [sea_orm (table_name = "user")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , # [sea_orm (unique)] pub email : String , pub hashed_password : String , pub first_name : Option < String > , pub last_name : Option < String > , pub created_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (has_many = "super::device::Entity")] Device , # [sea_orm (has_many = "super::reservoir::Entity")] Reservoir , }

impl Related < super :: device :: Entity > for Entity { fn to () -> RelationDef { Relation :: Device . def () } }

impl Related < super :: reservoir :: Entity > for Entity { fn to () -> RelationDef { Relation :: Reservoir . def () } }

impl ActiveModelBehavior for ActiveModel { }