//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq)] # [sea_orm (table_name = "system_settings")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub id : i32 , pub maintenance_mode : bool , pub registration_enabled : bool , pub default_data_retention_days : i32 , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { }

impl ActiveModelBehavior for ActiveModel { }